### ISSUE TITLE
运行 STEG_GEN.py 时，提示缺少配置文件错误

### ISSUE THREAD

**Issue by shuhuicoder** [yjs1224/TextSteg#1]
你好，当我试图运行项目中的STEG_GEN.py时，遇到了错误，
错误描述如下：
 configs = json.load(open(config_path, "r", encoding="utf-8"))
 FileNotFoundError: [Errno 2] No such file or directory: './Configs/commonsense-gpt-ac.json'
项目中的Configs目录下似乎缺少了“commonsense-gpt-ac.json”这样一个配置文件，请问是否方便提供呢？
谢谢

**Comment by yjs1224** [comment]
这是一个内部测试的配置文件，你可以改用为Configs/movie-ac.json
